// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import GeocodingController from "./geocoding_controller"
application.register("geocoding", GeocodingController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)
